server:
  port: 8208
spring:
  rabbitmq:
    host: ${behappy.rabbitmq.host:192.168.56.100}
    port: ${behappy.rabbitmq.port:5672}
    # 指定虚拟主机
    virtual-host: ${behappy.rabbitmq.virtual-host:/}
    username: ${behappy.rabbitmq.username:root}
    password: ${behappy.rabbitmq.password:root}
    # 开启发送端确认
    publisher-confirm-type: correlated
    #　开启发送端消息抵达队列确认
    publisher-returns: true
    # 只要抵达队列，以异步优先回调我们这个 return/confirm
    template:
      mandatory: true
    # 手动ack消息 消息不容易丢失
    listener:
      simple:
        acknowledge-mode: manual
thread:
  pool:
    name-prefix: @project.artifactId@
logging:
  config: classpath:logback-spring.xml
xxl:
  job:
    #调度中心通讯TOKEN [选填]：非空时启用
    accessToken: default_token
    admin:
      addresses: ${behappy.xxl-admin.addresses:http://192.168.56.100:8080/xxl-job-admin}
    executor:
      #执行器IP，默认为空表示自动获取IP
      ip: ''
      address: ''
      #xxljob配置的端口号，默认为9999
      port: 9999
      #xxljob配置的执行器名称，
      appname: @project.artifactId@
      #执行器运行日志文件存储磁盘路径
      logpath: /data/applogs/xxl-job/jobhandler
      #调度中心日志表数据保存天数，过期日志自动清理；限制大于等于7时生效，否则, 如-1，关闭自动清理功能
      logretentiondays: 7
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
