spring:
  rabbitmq:
    host: 192.168.56.103
    port: 5672
    # 指定虚拟主机
    virtual-host: /
    username: root
    password: root
    # 开启发送端确认
    publisher-confirm-type: simple
    #　开启发送端消息抵达队列确认
    publisher-returns: true
    # 只要抵达队列，以异步优先回调我们这个 return/confirm
    template:
      mandatory: true
    # 手动ack消息 消息不容易丢失
    listener:
      simple:
        acknowledge-mode: manual
  redis:
    redisson:
      file: classpath:redisson.yaml
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
feign:
  sentinel:
    enabled: true
aliyun:
  sms:
    access-key-id: xxx
    access-key-secret: xxx
    sign-name: ABC商城
    template-code: SMS_206546316