spring:
  redis:
    redisson:
      file: classpath:redisson.yaml
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
feign:
  sentinel:
    enabled: true
aliyun:
  sms:
    access-key-id: xxx
    access-key-secret: xxx
    sign-name: xxx
    template-code: xxx
