server:
  port: 8203
spring:
  security:
    user:
      name: root
      password: root
  boot:
    admin:
      context-path: '/'

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
