spring:
  cloud:
    openfeign:
      okhttp:
        enabled: false
      httpclient:
        enabled: true
        max-connections: 200 # 最大的连接数
        max-connections-per-route: 50 # 每个路径的最大连接数
      client:
        config:
          default: # default全局的配置
            loggerLevel: basic # 日志级别，BASIC就是基本的请求和响应信息
            connectTimeout: 10000
            readTimeout: 10000
      compression:
        request:
          enabled: true
        response:
          enabled: true
      # https://github.com/alibaba/spring-cloud-alibaba/issues/3024
      lazy-attributes-resolution: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${behappy.mysql.password:root}
    username: ${behappy.mysql.username:root}
    url: jdbc:mysql://${behappy.mysql.host:192.168.56.100:3306}/${behappy.mysql.db.cmn:yygh_cmn}?allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    druid:
      aop-patterns: org.xiaowu.behappy.*  #监控SpringBean
      filters: stat,wall     # 底层开启功能，stat（sql监控），wall（防火墙）
      stat-view-servlet:   # 配置监控页功能
        enabled: true
        login-username: ${behappy.druid.login-username:admin}
        login-password: ${behappy.druid.login-password:admin}
        resetEnable: false
      web-stat-filter:  # 监控web
        enabled: true
        urlPattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      filter:
        stat:    # 对上面filters里面的stat的详细配置
          slow-sql-millis: 1000
          logSlowSql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false
# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  global-config:
    banner: false
    db-config:
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    # sql日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
thread:
  pool:
    name-prefix: @project.artifactId@
feign:
  sentinel:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
