server:
  port: 8202
spring:
  redis:
    redisson:
      file: classpath:redisson.yaml
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/yygh_cmn?allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
# ???
# mybaits-plus??
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  global-config:
    banner: false
    db-config:
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    #??sql??
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# redis
behappy:
  redis:
    # runner??
    banner-shown: true
    # CacheManager????
    cache-manager:
      # ??cache ??
      prefix: BEHAPPY
      configs:
        - key: test
          # ????
          ttl: 0
          # ??????
          maxIdleTime: 0
          maxSize: 0
