server:
  port: 8205
aliyun:
  oss:
    access-key-id:
    access-key-secret:
    bucket: behappy-xiaowu
    endpoint: oss-cn-beijing.aliyuncs.com
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
thread:
  pool:
    name-prefix: @project.artifactId@
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS