spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    # 指定虚拟主机
    virtual-host: /
    username: root
    password: root
    # 开启发送端确认
    publisher-confirm-type: simple
    #　开启发送端消息抵达队列确认
    publisher-returns: true
    # 只要抵达队列，以异步优先回调我们这个 return/confirm
    template:
      mandatory: true
    # 手动ack消息 消息不容易丢失
    listener:
      simple:
        acknowledge-mode: manual
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    username: root
    url: jdbc:mysql://127.0.0.1:3306/yygh_hosp?allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
  data:
    #uri: mongodb://用户名:密码@服务器IP:端口/数据库名
    # 上方为明确指定某个数据的用户进行连接
    # 也可以使用admin 数据库中的用户进行连接  统一到admin 数据库进行认证
    # admin 用户认证 url 写法： mongodb://账户:密码@ip:端口/数据库名?authSource=admin&authMechanism=SCRAM-SHA-1
    mongodb:
      uri: mongodb://root:root@127.0.0.1:27017/yygh_hosp?authSource=admin&authMechanism=SCRAM-SHA-1
# 数据源
# mybaits-plus配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  global-config:
    banner: false
    db-config:
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    #开启sql日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
feign:
  sentinel:
    enabled: true
