spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: behappy-hosp
          uri: lb://behappy-hosp
          predicates:
            - Path=/api/*/hosp/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: behappy-cmn
          uri: lb://behappy-cmn
          predicates:
            - Path=/api/*/cmn/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: behappy-user
          uri: lb://behappy-user
          predicates:
            - Path=/api/*/user/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: behappy-user
          uri: lb://behappy-user
          predicates:
            - Path=/api/*/ucenter/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: behappy-msm
          uri: lb://behappy-msm
          predicates:
            - Path=/api/*/msm/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}