server:
  port: 8088

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: behappy-hosp
          uri: lb://behappy-hosp
          predicates:
            - Path=/*/hosp/**
#          filters:
#            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: behappy-cmn
          uri: lb://behappy-cmn
          predicates:
            - Path=/*/cmn/**
        - id: behappy-user
          uri: lb://behappy-user
          predicates:
            - Path=/*/user/**
        - id: behappy-user
          uri: lb://behappy-user
          predicates:
            - Path=/*/ucenter/**
        - id: behappy-msm
          uri: lb://behappy-msm
          predicates:
            - Path=/*/msm/**
        - id: behappy-oss
          uri: lb://behappy-oss
          predicates:
            - Path=/*/oss/**
        - id: behappy-order
          uri: lb://behappy-order
          predicates:
            - Path=/*/order/**
thread:
  pool:
    name-prefix: @project.artifactId@
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS