name: 'GitHub Actions pushEmail Bot'

on:
  push:
    branches: [ "master","springboot2","springboot3" ]
  pull_request:
    branches: [ "master","springboot2","springboot3" ]

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Get pushEmail'
        run: bash ./pushEmail.sh Dalian
      - name: 'Get Date'
        run: echo "REPORT_DATE=$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')" >> $GITHUB_ENV
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.163.com
          server_port: 25
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: PushEmail Report (${{env.REPORT_DATE}})
          body: file://result.html
          to: a943915349@gmail.com
          from: GitHub Actions
          content_type: text/html
